-- MySQL Script generated by MySQL Workbench
-- 09/28/16 23:50:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema natekrank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema natekrank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `natekrank` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `natekrank` ;

-- -----------------------------------------------------
-- Table `natekrank`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`users` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` LONGTEXT NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `first_name` VARCHAR(1024) NULL COMMENT '',
  `last_name` VARCHAR(1024) NULL COMMENT '',
  `enabled` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natekrank`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`tasks` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `owner_id` INT NULL COMMENT '',
  `name` VARCHAR(255) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `days_expired` INT NULL COMMENT '',
  `minutes_for_solving` INT NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `owner_id_idx` (`owner_id` ASC)  COMMENT '',
  CONSTRAINT `owner_id`
  FOREIGN KEY (`owner_id`)
  REFERENCES `natekrank`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natekrank`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`questions` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `task_id` INT NULL COMMENT '',
  `text` TEXT NULL COMMENT '',
  `multiselect` TINYINT(1) NULL COMMENT '',
  `orderNum` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `task_id_idx` (`task_id` ASC)  COMMENT '',
  CONSTRAINT `task_id`
  FOREIGN KEY (`task_id`)
  REFERENCES `natekrank`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natekrank`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`answers` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `question_id` INT NULL COMMENT '',
  `text` VARCHAR(2048) NULL COMMENT '',
  `is_right` TINYINT(1) NULL COMMENT '',
  `orderNum` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `question_id_idx` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `question_id`
  FOREIGN KEY (`question_id`)
  REFERENCES `natekrank`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natekrank`.`surveys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`surveys` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`surveys` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `task_id` INT NULL COMMENT '',
  `sender` VARCHAR(255) NULL COMMENT '',
  `survey_key` VARCHAR(8) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `message` TEXT NULL COMMENT '',
  `sent` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `first_name` VARCHAR(1024) NULL COMMENT '',
  `last_name` VARCHAR(1024) NULL COMMENT '',
  `due_to` DATETIME NULL COMMENT '',
  `minutes_for_solving` INT NULL COMMENT '',
  `started` DATETIME NULL DEFAULT NULL COMMENT '',
  `finished` DATETIME NULL DEFAULT NULL COMMENT '',
  `sender_notified` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `score` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_survey_task_id` (`task_id` ASC)  COMMENT '',
  CONSTRAINT `fk_survey_task_id`
  FOREIGN KEY (`task_id`)
  REFERENCES `natekrank`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natekrank`.`survey_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`survey_answers` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`survey_answers` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `question_id` INT NULL COMMENT '',
  `survey_id` INT NULL COMMENT '',
  `selected_answer_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `idx_survey_id` (`survey_id` ASC)  COMMENT '',
  INDEX `idx_answer_id` (`selected_answer_id` ASC)  COMMENT '',
  INDEX `idx_question_id` (`question_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sv_ticket_id`
  FOREIGN KEY (`survey_id`)
  REFERENCES `natekrank`.`surveys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sv_selected_answer_id`
  FOREIGN KEY (`selected_answer_id`)
  REFERENCES `natekrank`.`answers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sv_question_id`
  FOREIGN KEY (`question_id`)
  REFERENCES `natekrank`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `natekrank`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `natekrank`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `natekrank`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT NULL COMMENT '',
  `role` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_roles_user_id_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_roles_user_id`
  FOREIGN KEY (`user_id`)
  REFERENCES `natekrank`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO users(email, password, first_name, last_name, enabled)
VALUES('test@natek.pl', '1', 'Test', 'Test', true);

INSERT INTO user_roles(user_id, role)
VALUES(1, 'ROLE_ADMIN');

INSERT INTO tasks(owner_id, name, description, days_expired, minutes_for_solving)
VALUES(1, 'Task #1', 'Task #1 description', 7, 90);